import {
  DataGrid,
  gridPageCountSelector,
  gridPageSelector,
  useGridApiContext,
  useGridSelector,
} from "@mui/x-data-grid";
import { Button, Pagination, TextField, Box } from "@mui/material";

import { useState, useEffect } from "react";
import axios from "axios";

import { useNavigate } from "react-router-dom";

const dummycolumns = [
  {
    field: "id",
    headerName: "ID",
    flex: 1,
    disableColumnMenu: true,
    headerAlign: "center",
    sortable: true,
    align: "center",
  },
  {
    field: "name",
    headerName: "이름",
    flex: 3,
    disableColumnMenu: true,
    headerAlign: "center",
    sortable: true,
    align: "center",
  },
  {
    field: "position",
    headerName: "직책",
    flex: 3,
    sortable: true,
    headerAlign: "center",
    disableColumnMenu: true,
    align: "center",
    valueFormatter: (params) => {
      return "교수";
    },
  },
  {
    field: "major",
    headerName: "전공",
    flex: 3,
    sortable: true,
    headerAlign: "center",
    disableColumnMenu: true,
    align: "center",
  },
  {
    field: "email",
    headerName: "이메일",
    sortable: true,
    flex: 3,
    headerAlign: "center",
    disableColumnMenu: true,
    align: "center",
  },
];

const dummy = {
  position: "professor",
  members: [
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 26,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 0,
      name: "나승훈",
      major: "인공지능",
      email: "nash@jbnu.ac.kr",
    },
    {
      id: 1,
      name: "김성찬",
      major: "인공지능",
      email: "s.kim@jbnu.ac.kr",
    },
    {
      id: 2,
      name: "오일석",
      major: "컴퓨터비전",
      email: "isoh@jbnu.ac.kr",
    },
    {
      id: 3,
      name: "이경순",
      major: "정보마이닝",
      email: "selfsolee@jbnu.ac.kr",
    },
    {
      id: 4,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 5,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 6,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 7,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 8,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 9,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 10,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 11,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 12,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 13,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 14,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 15,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 16,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 17,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 18,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 19,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 20,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 21,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 22,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 23,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 24,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 25,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
    {
      id: 3000,
      name: "이준환",
      major: "인공지능",
      email: "chlee@jbnu.ac.kr",
    },
  ],
};

/**
 *@author Suin-Jeong suin8@jbnu.ac.kr
 *@date 2022-09-09
 *@description Admin Professor 페이지
 *             DataGrid 이용
 */

const Professor = ({ addMainText }) => {
  const [data, setData] = useState({ position: "", members: [] });
  const navigate = useNavigate();

  useEffect(() => {
    // axios({
    //   method: "get",
    //   url: "https://8d020d2f-f787-45d5-88de-64d4ae1c030c.mock.pstmn.io/members/professor",
    //   responseType: "json",
    // }).then((response) => {
    //   setData(response.data);
    // });
    setData(dummy);
  }, []);

  return (
    <div
      style={{
        paddingTop: "3%",
        paddingBottom: "3%",
        paddingLeft: "7.5%",
        paddingRight: "7.5%",
      }}
    >
      <Box sx={{ display: "flex", mb: "2%", justifyContent: "flex-end" }}>
        <TextField
          id="outlined-basic"
          label="Search"
          variant="outlined"
          sx={{
            width: "20%",
            display: "flex",
            justifyContent: "right",
            mr: "3%",
          }}
        />
        <Button
          variant="contained"
          size="large"
          onClick={() => {
            addMainText("등록하기");
            navigate(`./new`);
          }}
        >
          등록하기
        </Button>
      </Box>
      <div style={{ height: "70vh" }}>
        <DataGrid
          rows={data.members}
          columns={dummycolumns}
          sortingOrder={["desc", "asc"]}
          hideFooterSelectedRowCount
          sx={{ cursor: "pointer" }}
          onRowClick={(param) => {
            addMainText("상세보기");
            navigate(`${param.row.id}`);
          }}
        />
      </div>
    </div>
  );
};

export default Professor;
